services:
  proxy:
    image: tivix/docker-nginx:v16
    environment:
      - UPSTREAMS=/:backend:8000
    ports:
      - 8080:80
    depends_on:
      backend:
        condition: service_started
    networks:
      - default

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    command: ["dev"]
    networks:
      - default
    depends_on:
      - selenium-chrome

  selenium-chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    shm_size: '2gb'
    networks:
      - default

networks:
  default:
    driver: bridge
